Repository cyberark/secrets-provider-for-k8s, pull requests merged in 2022-02, with the labels that each got.

#435 Upgrade to latest go modules
  go.mod
  go.sum
Labels: kind/dependency-vulnerability

#441 Fix OpenShift test for rotation
  deploy/config/openshift/test-env-secrets-rotation.sh.yml
Labels: kind/failing-test

#443 Adding documentation for Secrets Rotation
  PUSH_TO_FILE.md
  README.md
  ROTATION.md
  design/how-secrets-rotation-works.png
  pkg/log/messages/error_messages.go
Labels: kind/documentation
