Repository cyberark/secrets-provider-for-k8s, pull requests merged in 2022-03, with the labels that each got.

#446 Don't overwrite secret file if atomic temp file not written
  pkg/atomicwriter/atomic_writer.go
  pkg/atomicwriter/atomic_writer_test.go
  pkg/log/messages/error_messages.go
  pkg/secrets/pushtofile/push_to_writer.go
Labels: kind/bug

#447 Delete secrets files when retrieval fails
  CHANGELOG.md
  ROTATION.md
  cmd/secrets-provider/main.go
  deploy/policy/templates/conjur-delete-secret.template.sh.yml
  deploy/test/test_cases/TEST_ID_28_secrets_rotation.sh
  pkg/log/messages/info_messages.go
  pkg/secrets/config/config.go
  pkg/secrets/config/config_test.go
  pkg/secrets/provide_conjur_secrets.go
  pkg/secrets/pushtofile/provide_conjur_secrets.go
  pkg/secrets/pushtofile/provide_conjur_secrets_test.go
Labels: kind/enhancement

#442 Update Push-to-File docs: clarify secret file path default cases
  PUSH_TO_FILE.md
Labels: kind/documentation
